# Generated by Django 3.1.1 on 2020-10-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0009_forumjoined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ST', 'Student'), ('IN', 'Instructor')], default='ST', max_length=2),
        ),
    ]
