# Generated by Django 3.1.1 on 2020-10-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0010_customuser_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-date_posted',)},
        ),
    ]
