name: CI/CD Test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

env:
  DEPLOY_PHASE: ${{ secrets.DEPLOY_PHASE }}
  DEBUG: 'True'
  DATABASE_UNAME: ${{ secrets.DATABASE_UNAME }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PWD: ${{ secrets.DATABASE_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version:  '3.7'
      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials

          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region = ${{ secrets.AWS_DEFAULT_REGION }}" > ~/.aws/credentials
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install, Test, Deploy
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv .venv
          source ./.venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py test
          pip install zappa
          zappa update dev