name: CI/CD Test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

env:
  DEPLOY_PHASE: ${{ secrets.DEPLOY_PHASE }}
  DEBUG: 'True'
  DATABASE_UNAME: ${{ secrets.DATABASE_UNAME }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PWD: ${{ secrets.DATABASE_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:  '3.7'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Migrate Database Changes
      run: |
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Deploy to Lambda
      run: |
        pip install zappa
        zappa update dev
